---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: local-app
  namespace: core-local
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: "glob:master-*"
spec:
  values:
    image:
      repository: nginx
      tag: latest
    replicaCount: 1
    namespace: core-local
    environment: local
    annotations:
      prometheus.io/port: "9000"
      prometheus.io/scrape: "false"
    podAnnotations: {}
    metrics:
      serviceMonitor:
        enabled: true
        scrapeInterval: 10s

    nameOverride: ""
    fullnameOverride: ""
    service:
      type: ClusterIP
      port: 80
      annotations: {}

    ingress:
      enabled: true
      host: localhost
      annotations: {}
      hosts:
        - localhost
      tls:
        - secretName: localhost
          hosts:
            - localhost
    env:
      WP_HOME: "http://localhost"

    secrets:
      db_host: ""
      db_username: ""
      db_password: ""

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 5m
        memory: 100Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}
  releaseName: local-app
  chart:
    git: git@github.com:appasahebs/k8s-local.git
    ref: master
    path: charts/app
